services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  meter-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
      MONGO_URL: mongodb://root:example@mongodb:27017
      BSV_NETWORK: main
    depends_on:
      - mongodb

  meter-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - meter-back

volumes:
  mongo-data:
